name: Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies    
      run: npm install
      
    - name: Start the server    
      run: npm run server &
      
    - name: Start the app    
      run: npm start &

    - name: Install Playwright
      run: npx playwright install
      
    - name: Start tests 
      run: npm test

  deploy_server:
    needs: build_tests

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
    - name: Deploy server to Render
      uses: JorgeLNJunior/render-deploy@v1.4.7
      with:
        service_id: ${{ secrets.BE_RENDER_SERVICE_ID }}
        api_key: ${{ secrets.BE_RENDER_API_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        wait_deploy: true

  deploy_app:
    needs: deploy_server

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
    - name: Deploy app to Render
      uses: JorgeLNJunior/render-deploy@v1.4.7
      with:
        service_id: ${{ secrets.FE_RENDER_SERVICE_ID }}
        api_key: ${{ secrets.FE_RENDER_API_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        wait_deploy: true
